# 2. Basic Knowledge_Numerical Python

## Numpy Libarary

In [1]:
import numpy as np

## 2.1. Array : 

### A multidimensional set of numbers

### - Vector: one_dimentional array

In [6]:
Array_exp_1= np.array([3,5,7])
Array_exp_1

array([3, 5, 7])

In [7]:
Array_exp_2= np.array([2,4,6])
print(Array_exp_2)

[2 4 6]


### - Matrix: two (or more)_dimentional array

#### - 2D Matrix: two_dimentional array

In [16]:
Array_2d_exp_1= np.array([[3,5,7],[2,4,6]])
print(Array_2d_exp_1)

[[3 5 7]
 [2 4 6]]


In [27]:
Array_2d_exp_2= np.array([[1,3,5],[0,8,10]])
print(Array_2d_exp_2)

[[ 1  3  5]
 [ 0  8 10]]


#### - 3D Matrix: three_dimentional array

In [56]:
Array_3d_exp_1= np.array([[[3,5,7],[2,4,6]], [[3,5,7],[2,4,6]]])
print(Array_3d_exp_1)

[[[3 5 7]
  [2 4 6]]

 [[3 5 7]
  [2 4 6]]]


## 2.2. Sum of arrays

In [31]:
print("Vector1:", Array_exp_1)
print("Vector2:", Array_exp_2)
print("Summation of Vector1 & Vector2:",Array_exp_1+Array_exp_2)

Vector1: [3 5 7]
Vector2: [2 4 6]
Summation of Vector1 & Vector2: [ 5  9 13]


In [33]:
print("Matrix1:\n", Array_2d_exp_1)
print("Matrix2:\n", Array_2d_exp_2)
print("Summation of Matrix1 & Matrix2:\n",Array_2d_exp_1+Array_2d_exp_2)

Matrix1:
 [[3 5 7]
 [2 4 6]]
Matrix2:
 [[ 1  3  5]
 [ 0  8 10]]
Summation of Matrix1 & Matrix2:
 [[ 4  8 12]
 [ 2 12 16]]


## 2.3. Attribute of arrays

### - Number of Dimension:  *array.ndim*

In [39]:
print('Dimension of Array_exp:', Array_exp_1.ndim)
print('Dimension of Array_2d_exp:', Array_2d_exp_1.ndim)
print('Dimension of Array_3d_exp:', Array_3d_exp_1.ndim)

Dimension of Array_exp: 1
Dimension of Array_2d_exp: 2
Dimension of Array_3d_exp: 3


### - Data type:  *array.dtype*

In [45]:
print('Type of Array_exp:', Array_exp_1.dtype)
print('Type of Array_2d_exp:', Array_2d_exp_1.dtype)
print('Type of Array_3d_exp:', Array_3d_exp_1.dtype)

Type of Array_exp: int32
Type of Array_2d_exp: int32
Type of Array_3d_exp: <U11


### - Determine the type of data in an array


In [46]:
Array_exp_4= np.array([3,5,7], float)

print('Type of Array_exp4:', Array_exp_4.dtype)

Type of Array_exp4: float64


### - Shape of an array:  *np.shape(array)*  or *array.shape*


In [48]:
print('Shape of Array_exp:', np.shape(Array_exp_1))
print('Shape of Array_2d_exp:', np.shape(Array_2d_exp_1))
print('Shape of Array_3d_exp:', Array_3d_exp_1.shape)

Shape of Array_exp: (3,)
Shape of Array_2d_exp: (2, 3)
Shape of Array_3d_exp: (2, 2, 3)


## 2.4. Sum of elements

### sume all elementsin an array: *np.sum()*

In [51]:
print('Array_exp:', Array_exp_1)
print('summation of all elements in Array_exp:', np.sum(Array_exp_1))

Array_exp: [3 5 7]
summation of all elements in Array_exp: 15


In [54]:
print('Array_2d_exp:\n', Array_2d_exp_1)
print('summation of all elements in Array_2d_exp:', np.sum(Array_2d_exp_1),'=', Array_2d_exp_1[0,0],'+',
      Array_2d_exp_1[0,1],'+', Array_2d_exp_1[0,2],'+', Array_2d_exp_1[1,0],'+', Array_2d_exp_1[1,1],'+',
      Array_2d_exp_1[1,2])

Array_2d_exp:
 [[3 5 7]
 [2 4 6]]
summation of all elements in Array_2d_exp: 27 = 3 + 5 + 7 + 2 + 4 + 6


In [57]:
print('Array_3d_exp:\n', Array_3d_exp_1)
print('summation of all elements in Array_3d_exp:', np.sum(Array_3d_exp_1))

Array_3d_exp:
 [[[3 5 7]
  [2 4 6]]

 [[3 5 7]
  [2 4 6]]]
summation of all elements in Array_3d_exp: 54


## 2.4. Reshape Array: *np.reshape()*  or *array.reshape()*

In [68]:
Array_exp_5=np.array([1,2,3,4,5,6])
print('Array_exp:', Array_exp_5)
print('Shape of Array_exp:', Array_exp_5.shape,'\n')
Array_exp_5_reshape=np.reshape(Array_exp_5, (2,3))
print('Reshaped Array_exp:\n', np.reshape(Array_exp_5, (2,3)))
print('Shape of Reshaped Array_exp:', np.reshape(Array_exp_5, (2,3)).shape)

Array_exp: [1 2 3 4 5 6]
Shape of Array_exp: (6,) 

Reshaped Array_exp:
 [[1 2 3]
 [4 5 6]]
Shape of Reshaped Array_exp: (2, 3)


#### Changes made to the reshaped array will also affect the original array.

In [69]:
print('Array before we modify Array_reshape:\n', Array_exp_5)
print('Array_reshape before we modify Array_reshape:\n', Array_exp_5_reshape)
Array_exp_5_reshape[0, 0] = 5
print('Array_reshape after we modify its top left element:\n',
Array_exp_5_reshape)
print('Array after we modify top left element of Array_reshape:\n', Array_exp_5)

Array before we modify Array_reshape:
 [1 2 3 4 5 6]
Array_reshape before we modify Array_reshape:
 [[1 2 3]
 [4 5 6]]
Array_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
Array after we modify top left element of Array_reshape:
 [5 2 3 4 5 6]


## 2.5. Generating Random Number

### N(0,1)

In [73]:
Data_exmp_1=np.random.normal(size=50)
Data_exmp_1

array([-0.42473096,  0.86790096, -0.57627322, -1.0891415 , -0.80931664,
        0.60291971, -0.6120208 ,  0.30163992, -0.8859165 ,  1.67219498,
       -1.3167247 ,  1.88400124, -0.12759145,  1.05750005, -0.23401461,
       -1.38867558,  0.10323313, -2.32569142, -0.99155477, -0.07045048,
       -1.66262071, -0.35154289, -0.37857585,  0.12839694, -1.41518864,
        1.60712332,  0.49882965, -0.23841137, -0.92077903,  0.59259073,
        0.89872729, -0.28253489,  1.1700055 , -1.52213929, -0.1975795 ,
       -1.31023631,  1.64991492, -0.72005315, -0.12606725, -1.29186129,
        0.65170427,  0.67043536, -0.69434347, -0.28522317, -0.07116582,
        1.58013825, -0.50801773, -1.31013411,  1.01750622, -0.69842587])

### N(mu,sigma)


In [74]:
mu=50
sigma=10
Data_exmp_2=np.random.normal(loc=mu, scale=sigma, size=50)
Data_exmp_2

array([59.75642423, 45.45512461, 59.44881044, 56.89621688, 31.00169636,
       54.80376757, 47.10715157, 46.27983691, 47.29549062, 78.02565999,
       63.92644426, 60.15863097, 43.58206584, 42.41709692, 49.2570114 ,
       31.34559773, 51.84406963, 39.81210097, 36.69294051, 45.27738771,
       41.69336287, 32.8983093 , 41.264058  , 46.30888941, 62.56539547,
       63.49973689, 57.74449488, 47.94506307, 25.13142202, 44.12299295,
       25.93380878, 50.48815633, 46.62720923, 70.74534216, 56.07214618,
       51.98173848, 39.08074747, 52.91814892, 47.87091611, 63.69890372,
       29.37628677, 61.16729227, 39.13094609, 34.65941704, 62.51699321,
       36.57042047, 57.42844221, 50.01208932, 42.35219302, 54.0326628 ])

## 2.6. Corrolation between two array: *np.corrcoef()*


In [80]:
Data_exmp_3=Data_exmp_1+Data_exmp_2
print('Corrolation Matrix:\n', np.corrcoef(Data_exmp_3, Data_exmp_1))

Corrolation Matrix:
 [[1.         0.10924646]
 [0.10924646 1.        ]]


## 2.7. vector : *linspace()*

In [83]:
vector_exmp_1=np.linspace(0,10,50)
print('it returns a vector with 50 numbers between 0 and 10: \n\n', vector_exmp_1)

it returns a vector with 50 numbers between 0 and 10: 

 [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


## 2.8. $\pi$ : *np.pi*

In [92]:
pi_symbol = '\u03C0'
print(pi_symbol, '=', np.pi)

π = 3.141592653589793


## 2.9. Outer product of two arrays

In [93]:
# Define two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Compute the outer product
outer_product = np.multiply.outer(vector_a, vector_b)

# Display the result
print("Vector A:", vector_a)
print("Vector B:", vector_b)
print("Outer Product:\n", outer_product)


Vector A: [1 2 3]
Vector B: [4 5 6]
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## 2.10. Sine and Cosine of each element in an array

In [94]:
# Define an array of angles in radians
angles = np.array([0, np.pi/4, np.pi/2, np.pi])

# Compute the cosine of each angle
cosines = np.cos(angles)

# Display the result
print("Angles (radians):", angles)
print("Cosines:", cosines)


Angles (radians): [0.         0.78539816 1.57079633 3.14159265]
Cosines: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


## 2.11. Finding Unique value in an array

In [96]:
Array_exp_6=[1,2,3,4,4,5,6,8,3,2,6]
print("Array with unique element:", np.unique(Array_exp_6))

Array with unique element: [1 2 3 4 5 6 8]
